version: '3.7'

services:
  web:
    build: ./TradeApp
    command: sh -c "python manage.py migrate &&
                    python manage.py loaddata initial_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./TradeApp/:/usr/src/TradeApp/
    ports:
      - 8000:8000
    depends_on:
      - redis


  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  synctrades:
    build: ./TradeApp
    command: sh -c "python manage.py migrate && python sync_trades.py"
    volumes:
      - ./TradeApp/:/usr/src/TradeApp/
    depends_on:
      - redis
      - web